version: '2'
services:
    jhipstermysqlsampleapplication-app:
        image: jhipstermysqlsampleapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstermysqlsampleapplication-mysql:3306/jhipstermysqlsampleapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstermysqlsampleapplication-mysql:
        extends:
            file: mysql.yml
            service: jhipstermysqlsampleapplication-mysql
